// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: server_seed.
// - Entity ID: 102019aae7a02607cd5a95d91deba3ada2f.
// - Entity Version: 102019ab02df9d7704fa02e2c2a4eddc961.
// - Task ID: 6922dc78947327e7a027e741.
// - Task Root ID: 69226b8241e3ace1254f4ffd.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for ServerSeedModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ServerSeedModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  seed_value: string;
  seed_hash: string;
  is_active: boolean;
  next_seed_hash?: string | null;
  rotated_at?: string | null;
}

/**
 * ORM class for ServerSeed entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ServerSeedORM {
  private static instance: ServerSeedORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019aae7a02607cd5a95d91deba3ada2f';
    this.entityName = 'server_seed';
    this.entityVersion = '102019ab02df9d7704fa02e2c2a4eddc961';
    this.taskId = '6922dc78947327e7a027e741';
    this.taskRootId = '69226b8241e3ace1254f4ffd';
  }

  /**
   * Get singleton instance of ServerSeedORM
   */
  public static getInstance(): ServerSeedORM {
    if (!ServerSeedORM.instance) {
      ServerSeedORM.instance = new ServerSeedORM();
    }
    
    return ServerSeedORM.instance;
  }

  /**
   * Get all ServerSeed records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllServerSeed(): Promise<ServerSeedModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ServerSeed record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertServerSeed(data: ServerSeedModel[]): Promise<ServerSeedModel[]> {
    const structured = data.map((item) => CreateData(ServerSeedModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ServerSeed records
   */
  async purgeAllServerSeed(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ServerSeed records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listServerSeed(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ServerSeedModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get server_seed by Id index
   * This function gets data by index.
   */
  async getServerSeedById(
    id: string,
  ): Promise<ServerSeedModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) server_seed by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setServerSeedById(
    id: string,
    data: ServerSeedModel
  ): Promise<ServerSeedModel[]> {
    const index = createIndexId(
      id
    );

    const values = ServerSeedModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete server_seed by Id index
   */
  async deleteServerSeedById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get server_seed by SeedHash index
   * This function gets data by index.
   */
  async getServerSeedBySeedHash(
    seed_hash: string,
  ): Promise<ServerSeedModel[]> {
    const index = createIndexSeedHash(
      seed_hash
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) server_seed by SeedHash index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setServerSeedBySeedHash(
    seed_hash: string,
    data: ServerSeedModel
  ): Promise<ServerSeedModel[]> {
    const index = createIndexSeedHash(
      seed_hash
    );

    const values = ServerSeedModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete server_seed by SeedHash index
   */
  async deleteServerSeedBySeedHash(
    seed_hash: string
  ): Promise<void> {
    const index = createIndexSeedHash(
      seed_hash
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get server_seed by IsActive index
   * This function gets data by index.
   */
  async getServerSeedByIsActive(
    is_active: boolean,
  ): Promise<ServerSeedModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) server_seed by IsActive index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setServerSeedByIsActive(
    is_active: boolean,
    data: ServerSeedModel
  ): Promise<ServerSeedModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const values = ServerSeedModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete server_seed by IsActive index
   */
  async deleteServerSeedByIsActive(
    is_active: boolean
  ): Promise<void> {
    const index = createIndexIsActive(
      is_active
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get server_seed by DataCreator index
   * This function gets data by index.
   */
  async getServerSeedByDataCreator(
    data_creator: string,
  ): Promise<ServerSeedModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) server_seed by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setServerSeedByDataCreator(
    data_creator: string,
    data: ServerSeedModel
  ): Promise<ServerSeedModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ServerSeedModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete server_seed by DataCreator index
   */
  async deleteServerSeedByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get server_seed by DataUpdater index
   * This function gets data by index.
   */
  async getServerSeedByDataUpdater(
    data_updater: string,
  ): Promise<ServerSeedModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) server_seed by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setServerSeedByDataUpdater(
    data_updater: string,
    data: ServerSeedModel
  ): Promise<ServerSeedModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ServerSeedModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete server_seed by DataUpdater index
   */
  async deleteServerSeedByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ServerSeedModel data array
   */
  private resultToData(values: Data[]): ServerSeedModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ServerSeedModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ServerSeedModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ServerSeedModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ServerSeedModel => item !== null);
  }
}

/**
 * Convert ServerSeedModel data to Value array
 */
function ServerSeedModelToValues(data: ServerSeedModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'seed_value', type: DataType.string, defaultValue: '' },
    { key: 'seed_hash', type: DataType.string, defaultValue: '' },
    { key: 'is_active', type: DataType.boolean, defaultValue: false },
    { key: 'next_seed_hash', type: DataType.string, defaultValue: null },
    { key: 'rotated_at', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ServerSeedModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ServerSeedModel data
 */
function ServerSeedModelFromValues(values: Value[]): ServerSeedModel {
  const data: Partial<ServerSeedModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'seed_value':
        data.seed_value = ParseValue(value, DataType.string) as string;
        break;
      case 'seed_hash':
        data.seed_hash = ParseValue(value, DataType.string) as string;
        break;
      case 'is_active':
        data.is_active = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'next_seed_hash':
        data.next_seed_hash = ParseValue(value, DataType.string) as string | null;
        break;
      case 'rotated_at':
        data.rotated_at = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as ServerSeedModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for SeedHash fields
 */
function createIndexSeedHash(
  seed_hash: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, seed_hash, 'seed_hash'),
  ];

  return {
    fields: ['seed_hash'],
    values
  };
}
/**
 * Create index for IsActive fields
 */
function createIndexIsActive(
  is_active: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_active, 'is_active'),
  ];

  return {
    fields: ['is_active'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ServerSeedORM;