// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: game_session.
// - Entity ID: 102019aae7a02617096a323e5e38dd75437.
// - Entity Version: 102019ab02df9d7704fa02e2c2a4eddc961.
// - Task ID: 6922dc78947327e7a027e741.
// - Task Root ID: 69226b8241e3ace1254f4ffd.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for GameSessionStatus
 */
export enum GameSessionStatus {
  Unspecified = 0,
  PENDING = 1,
  WON = 2,
  LOST = 3,
  CANCELLED = 4,
}



/**
 * Interface for GameSessionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface GameSessionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  server_seed_id: string;
  client_seed: string;
  nonce: number;
  bet_amount: string;
  currency: string;
  outcome?: number | null;
  multiplier?: number | null;
  win_amount: string;
  status: GameSessionStatus;
  game_data?: string | null;
  completed_at?: string | null;
}

/**
 * ORM class for GameSession entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class GameSessionORM {
  private static instance: GameSessionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019aae7a02617096a323e5e38dd75437';
    this.entityName = 'game_session';
    this.entityVersion = '102019ab02df9d7704fa02e2c2a4eddc961';
    this.taskId = '6922dc78947327e7a027e741';
    this.taskRootId = '69226b8241e3ace1254f4ffd';
  }

  /**
   * Get singleton instance of GameSessionORM
   */
  public static getInstance(): GameSessionORM {
    if (!GameSessionORM.instance) {
      GameSessionORM.instance = new GameSessionORM();
    }
    
    return GameSessionORM.instance;
  }

  /**
   * Get all GameSession records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllGameSession(): Promise<GameSessionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new GameSession record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertGameSession(data: GameSessionModel[]): Promise<GameSessionModel[]> {
    const structured = data.map((item) => CreateData(GameSessionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all GameSession records
   */
  async purgeAllGameSession(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List GameSession records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listGameSession(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[GameSessionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get game_session by Id index
   * This function gets data by index.
   */
  async getGameSessionById(
    id: string,
  ): Promise<GameSessionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_session by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSessionById(
    id: string,
    data: GameSessionModel
  ): Promise<GameSessionModel[]> {
    const index = createIndexId(
      id
    );

    const values = GameSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_session by Id index
   */
  async deleteGameSessionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_session by UserId index
   * This function gets data by index.
   */
  async getGameSessionByUserId(
    user_id: string,
  ): Promise<GameSessionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_session by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSessionByUserId(
    user_id: string,
    data: GameSessionModel
  ): Promise<GameSessionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = GameSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_session by UserId index
   */
  async deleteGameSessionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_session by StatusUserId index
   * This function gets data by index.
   */
  async getGameSessionByStatusUserId(
    status: GameSessionStatus,
    user_id: string,
  ): Promise<GameSessionModel[]> {
    const index = createIndexStatusUserId(
      status,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_session by StatusUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSessionByStatusUserId(
    status: GameSessionStatus,
    user_id: string,
    data: GameSessionModel
  ): Promise<GameSessionModel[]> {
    const index = createIndexStatusUserId(
      status,
      user_id
    );

    const values = GameSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_session by StatusUserId index
   */
  async deleteGameSessionByStatusUserId(
    status: GameSessionStatus,
    user_id: string
  ): Promise<void> {
    const index = createIndexStatusUserId(
      status,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_session by ServerSeedId index
   * This function gets data by index.
   */
  async getGameSessionByServerSeedId(
    server_seed_id: string,
  ): Promise<GameSessionModel[]> {
    const index = createIndexServerSeedId(
      server_seed_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_session by ServerSeedId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSessionByServerSeedId(
    server_seed_id: string,
    data: GameSessionModel
  ): Promise<GameSessionModel[]> {
    const index = createIndexServerSeedId(
      server_seed_id
    );

    const values = GameSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_session by ServerSeedId index
   */
  async deleteGameSessionByServerSeedId(
    server_seed_id: string
  ): Promise<void> {
    const index = createIndexServerSeedId(
      server_seed_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_session by DataCreator index
   * This function gets data by index.
   */
  async getGameSessionByDataCreator(
    data_creator: string,
  ): Promise<GameSessionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_session by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSessionByDataCreator(
    data_creator: string,
    data: GameSessionModel
  ): Promise<GameSessionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = GameSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_session by DataCreator index
   */
  async deleteGameSessionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_session by DataUpdater index
   * This function gets data by index.
   */
  async getGameSessionByDataUpdater(
    data_updater: string,
  ): Promise<GameSessionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_session by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSessionByDataUpdater(
    data_updater: string,
    data: GameSessionModel
  ): Promise<GameSessionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = GameSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_session by DataUpdater index
   */
  async deleteGameSessionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to GameSessionModel data array
   */
  private resultToData(values: Data[]): GameSessionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return GameSessionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as GameSessionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized GameSessionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is GameSessionModel => item !== null);
  }
}

/**
 * Convert GameSessionModel data to Value array
 */
function GameSessionModelToValues(data: GameSessionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'server_seed_id', type: DataType.string, defaultValue: '' },
    { key: 'client_seed', type: DataType.string, defaultValue: '' },
    { key: 'nonce', type: DataType.number, defaultValue: 0 },
    { key: 'bet_amount', type: DataType.string, defaultValue: '' },
    { key: 'currency', type: DataType.string, defaultValue: '' },
    { key: 'outcome', type: DataType.number, defaultValue: null },
    { key: 'multiplier', type: DataType.number, defaultValue: null },
    { key: 'win_amount', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'game_data', type: DataType.string, defaultValue: null },
    { key: 'completed_at', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof GameSessionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to GameSessionModel data
 */
function GameSessionModelFromValues(values: Value[]): GameSessionModel {
  const data: Partial<GameSessionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'server_seed_id':
        data.server_seed_id = ParseValue(value, DataType.string) as string;
        break;
      case 'client_seed':
        data.client_seed = ParseValue(value, DataType.string) as string;
        break;
      case 'nonce':
        data.nonce = ParseValue(value, DataType.number) as number;
        break;
      case 'bet_amount':
        data.bet_amount = ParseValue(value, DataType.string) as string;
        break;
      case 'currency':
        data.currency = ParseValue(value, DataType.string) as string;
        break;
      case 'outcome':
        data.outcome = ParseValue(value, DataType.number) as number | null;
        break;
      case 'multiplier':
        data.multiplier = ParseValue(value, DataType.number) as number | null;
        break;
      case 'win_amount':
        data.win_amount = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as GameSessionStatus;
        break;
      case 'game_data':
        data.game_data = ParseValue(value, DataType.string) as string | null;
        break;
      case 'completed_at':
        data.completed_at = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as GameSessionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for StatusUserId fields
 */
function createIndexStatusUserId(
  status: GameSessionStatus,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['status', 'user_id'],
    values
  };
}
/**
 * Create index for ServerSeedId fields
 */
function createIndexServerSeedId(
  server_seed_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, server_seed_id, 'server_seed_id'),
  ];

  return {
    fields: ['server_seed_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default GameSessionORM;